spring:
  profiles:
    active: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  thymeleaf:
    cache: false