spring:
  profiles:
    active: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  thymeleaf:
    cache: false