spring:
  profiles:
    active: prod

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        javax:
          cache:
            missing_cache_strategy: create
        format_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  thymeleaf:
    cache: false
