CREATE SEQUENCE category_sequence START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE card_sequence START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE member_sequence START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE bookmark_sequence START WITH 1 INCREMENT BY 50;